apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: zyadhany/udagram-api-user:7
        name: backend-user
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "4024Mi"
            cpu: "250m"
          limits:
            memory: "5024Mi"
            cpu: "500m"                  
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret
        ports:
          - containerPort: 8080