apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
      - name: frontend
        image: mohamedebrahim979777/udagram-frontend:v6
        imagePullPolicy: Always
        resources:
           requests:
              memory: "64Mi"
              cpu: "75m"
           limits:
             memory: "128Mi"
             cpu: "88m"       
        
        ports:
        - containerPort: 80
      restartPolicy: Always