apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: mohamedebrahim979777/reverseproxy:v7
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
           requests:
              memory: "512Mi"
              cpu: "250m"
           limits:
             memory: "1024Mi"
             cpu: "500m"       
        
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: aws-secret
        ports:
        - containerPort: 8080
      restartPolicy: Always  