apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: mohamedebrahim979777/reverseproxy:v7 
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "512Mi"
            cpu: "500"
          limits:
           
            cpu: "600"       
        ports:
        - containerPort: 8080
      restartPolicy: Always