apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: mohamedebrahim979777/reverseproxy:v7 
        name: reverseproxy
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "75m"
          limits:
            memory: "128Mi"
            cpu: "88m"                  
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: aws-secret
        ports:
          - containerPort: 8080
      restartPolicy: Always