apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: mohamedebrahim979777/udagram-api-user:v7
        name: backend-user
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "75m"
          limits:
            memory: "128Mi"
            cpu: "88m"                  
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: aws-secret
        ports:
          - containerPort: 8080